---
title: "Reading List"
---

| Week | Title | Item | Note for Student |
|:----:|:------|:----:|:-----------------|
| 1    | Inequalities in health: definitions, concepts, and theories                                                                                                                                               | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/EF76D5F3-7680-B75D-B784-2806D85090F3.html) |                  |
| 1    | Australia's health 2020 - Social determinants of health                                                                                                                                                   | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/E0AFD946-8036-BFAD-6F96-61B382F93083.html)                               |                  |
| 1    | A glossary for health inequalities                                                                                                                                                                        | [<i class="fa fa-circle-plus fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/1A2EC97B-1C97-2517-728F-E2A2FC372D0E.html)  |                  |
| 2    | A public health model of the social determinants of health                                                                                                                                                | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/6EDD0EEB-5455-13AE-0C9C-94852D491816.html)                               |                  |
| 2    | Income inequality and depression: a systematic review and meta-analysis of the association and a scoping review of mechanisms                                                                             | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/C4B947E7-8AE0-D813-1962-B0F7E9ED02DA.html)                               |                  |
| 2    | Social determinants of health and health inequalities                                                                                                                                                     | [<i class="fa fa-thumbs-up fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/9D37C2ED-136A-5682-4C29-A46FE4386F30.html)    | Read chapter 7   |
| 3    | Measuring socio-economic position                                                                                                                                                                         | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/5698AD46-0DE9-4CCD-C031-B13C52715818.html)                               | Read chapter 4   |
| 3    | Measuring health and health inequalities                                                                                                                                                                  | [<i class="fa fa-thumbs-up fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/45906408-E5F6-AD61-30B0-20949FCFF6BD.html)                              | Read chapter 2   |
| 3    | Australia's Health 2018 (AIHW)                                                                                                                                                                            | [<i class="fa fa-thumbs-up fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/FFC7F194-6D29-5709-7EA1-5FEE693B61E7.html)                              |                  |
| 4    | Poverty in Australia 2020: Part 1 Overview                                                                                                                                                                | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/946CB765-70EE-7865-735B-78C2B17C417D.html)                                     |                  |
| 4    | Poverty in Australia 2020: Part 2 Who is affected?                                                                                                                                                        | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/136BF39C-ABE6-4109-9A62-2B36D8D36FAC.html)                                     |                  |
| 4    | Indicators of Inequalityfactsheet                                                                                                                                                                        | [<i class="fa fa-thumbs-up fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/89071ACB-7A0C-0D1A-E6F5-F05524094EC5.html)                              |                  |
| 5    | Review on the role of socioeconomic status in child health and development                                                                                                                                | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/CF8F3E00-240E-CB18-D999-B82A8F34E80C.html)                                     |                  |
| 5    | The health-promotingfamily: a conceptualframeworkforfuture research                                                                                                                                   | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/472E8E42-76FF-DF80-532B-DB943128AA69.html)                                     |                  |
| 5    | Children, poverty and health promotion in Australia                                                                                                                                                       | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/06EA57C6-9616-1298-E941-3B88F920C073.html)                                     |                  |
| 6    | Health across unequal lives                                                                                                                                                                               | [<i class="fa fa-thumbs-up fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/624D337F-22BD-D7F0-DA0F-2CCDEAAE84FB.html)                              | Read chapter 10  |
| 6    | Measuring the socio-economic status of women across the life course.                                                                                                                                      | [<i class="fa fa-thumbs-up fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/315371F7-EC34-2FA5-C345-5CFDF16AF8E0.html)                              |                  |
| 6    | Age and cause-of-death contributions to area socioeconomic, sex and remoteness differences in life expectancy in New South Wales, 2010-2012                                                               | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/8429BF28-3898-2180-4238-79F665DF7478.html)                                     |                  |
| 7    | If I had stable housing I would be a bit more receptive to having a job.factors influencing the effectiveness of Disability Employment Services reform                                                   | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/09345577-8AFC-535D-A2B6-014E9E308CF5.html)                                     |                  |
| 7    | Disability and public health research in Australia                                                                                                                                                        | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/F6999DA4-6DCC-EED7-33BE-9626AD6EF4FF.html)                                     |                  |
| 8    | Rethinking the use of ‘vulnerable’                                                                                                                                                                        | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/ABB00A8E-BF4F-4404-0821-ABF76FCA5FC1.html)                                     |                  |
| 8    | Social determinants and psychological distress among Aboriginal and Torres Strait islander adults in the Australian state of Victoria: A cross-sectional population based study                           | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/D2CEE13B-40FE-1902-C95D-0445CEB89A8B.html)                                     |                  |
| 8    | The socio-economic status of migrant populations in regional and rural Australia and its implications for future population policy                                                                        | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/39D17EED-931F-8E8E-ADBF-0969B605967F.html)                                     |                  |
| 9    | Out-of-pocket costs: hitting the most vulnerable hardest Grattan Institute submission to the Senate Standing Committee on Community Affairs Inquiry into the out-of-pocket costs in Australian healthcare | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/DB5E25A6-D466-B8EF-85F6-E607E4208393.html)                                     |                  |
| 9    | Inequity in physician visits: the case of the unregulatedfee market in Australia                                                                                                                         | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/6B6745C4-FB00-3924-CBD6-F8C8E9C65A2D.html)                                     |                  |
| 9    | Socioeconomic inequalities in waiting times for primary care across ten OECD countries                                                                                                                    | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/0FB978CF-77AD-60C1-B479-0C64C22BEB12.html)                                     |                  |
| 10   | Rising Pressures, New Scaffolding, Uncertain futures: Australia's social policy response to the COVID-19 pandemic                                                                                         | [<i class="fa fa-thumbs-up fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/65D000F7-C3F1-7BD1-DDA6-BEE9B1147AEB.html)                              |                  |
| 10   | Social Assistance Payments and food Insecurity in Australia: Evidencefrom t...                                                                                                                            | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/62B96EB2-2AE8-30F9-49A4-FE98815CF6D4.html)                                     |                  |
| 10   | The changing nature of the Australian welfare state: A critical analysis of...                                                                                                                            | [<i class="fa fa-prescription fa-lg"></i>](http://resourcelists.lib.deakin.edu.au/items/2F42AB58-B66C-802B-DB6C-FDCACDED94FE.html)                                     |                  |