---
title: 'Week 3: How Do We Understand SES and Health? Trends, Measurements and Outcomes'
---

## How do we measure SES? {.tabset}

### Income

-   Measured using equivalised household income, equivalised family income, one's own income or parent's income
-   Considered a major determinant of living standards
-   Strongly associated with health - social gradient shows that as income increases, health increases
-   Good indicator of SES for mid-age adults

### Education

-   Typically summarised using measures of school completion (e.g. completed year 12), highest level of educational attainment or parents' educational attainment
-   Highly correlated with income and occupation
-   strong links to health, with the higher a person's level of education and literacy, the better their health is likely to be
-   Good indicator of SES for young adults

### Employment/occupation

-   Measured via own employment status, parents' employment status, number of family members/people in household employed/unemployed, or the proportion employed/unemployed in a community
-   Occupation allocated people in socio-economic groups, and can be used for the individual worker or household members
-   As one's level if occupational prestige increases, health outcomes improve (perhaps due to higher level of control)
-   Good measure of SES for mid-age adults

### Place of residence

-   Measures SES through the ranking of areas, from the neighbourhood, suburb through to country level
-   Measured in Australia through Socioeconomic Indexes for Areas (SEIFA) mapping
-   Areas of disadvantage tend to have poorer outcomes
-   Good measure when other information unavailable

## {-}